FROM python:3.12-slim

WORKDIR /usr/src/core

COPY app/backend/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/backend ./backend

ENV PYTHONPATH=/usr/src/core:/usr/src/core/backend

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
