services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    networks:
      - internal_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  # smtp4dev: #  just for testing mail server
  #   image: rnwood/smtp4dev:v3
  #   restart: always
  #   ports:
  #     # Change the number before : to the port the web interface should be accessible on
  #     - '5000:80'
  #     # Change the number before : to the port the SMTP server should be accessible on
  #     - '2525:25'
  #     # Change the number before : to the port the IMAP server should be accessible on
  #     - '143:143'
  #   volumes:
  #     # This is where smtp4dev stores the database..
  #       - smtp4dev-data:/smtp4dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal_net
      - public_net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      FLET_FORCE_WEB_SERVER: "true"
      FLET_SERVER_PORT: "3000"
    depends_on:
      - backend
    networks:
      - public_net

networks:
  internal_net:
    driver: bridge
  public_net:
    driver: bridge

volumes:
  postgres_data:
