FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./app/frontend .

ENV FLET_FORCE_WEB_SERVER=true
ENV FLET_SERVER_PORT=3000

EXPOSE 3000

CMD ["python", "main.py"]