services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    container_name: redis
    ports:
      - "6379:6379"


  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '2525:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend
    command: bash -c 'fastapi dev --host 0.0.0.0 --port 8000'
    volumes:
      - ./app:/usr/src/core
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: x8_90*6ztco&bhm$ua22m!5%a&lz-eb=&bmx+cr527n6fb2jfd

    # - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_db    

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: celery_worker
    command: bash -c 'PYTHONPATH=/usr/src/core celery -A core.celery_conf.celery_app worker --loglevel=INFO'
    volumes:
      - ./app:/usr/src/core
    # does not need external port
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: x8_90*6ztco&bhm$ua22m!5%a&lz-eb=&bmx+cr527n6fb2jfd

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: celery_beat
    command: bash -c 'PYTHONPATH=/usr/src/core celery -A core.celery_conf.celery_app beat --loglevel=INFO'
    volumes:
      - ./app:/usr/src/core
    # does not need external port
    depends_on:
      db:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      JWT_SECRET_KEY: x8_90*6ztco&bhm$ua22m!5%a&lz-eb=&bmx+cr527n6fb2jfd

  flower:
    image: mher/flower:0.9.7
    command: ['flower', '--broker=redis://redis:6379/3', '--port=5555']
    ports:
      - 5555:5555
    depends_on:
      - redis

volumes:
  smtp4dev-data:
#   postgres_data:
